# cylonnet/docker-compose.yml
version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./cylonnet:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - cylonnet-net
    depends_on:
      - php

  php:
    build: .
    volumes:
      - ./cylonnet:/var/www/html
    networks:
      - cylonnet-net
    environment:
      - PHP_FPM_LISTEN=9000
    depends_on:
      - db

  db:
    image: mariadb:latest
    volumes:
      - ./mariadb/mariadb:/var/lib/mysql
      - ./mariadb/initdb:/docker-entrypoint-initdb.d 
    environment:
      MYSQL_ROOT_PASSWORD: cambia_esto
      MYSQL_DATABASE: CYLONNet
      MYSQL_USER: cylon_adm
      MYSQL_PASSWORD: cambia_esto
    networks:
      - cylonnet-net

networks:
  cylonnet-net: