# cylonnet/docker-compose.yml
version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./cylonnet:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d 
    networks:
      - cylonnet-net
    depends_on:
      - php

  php:
    build: 
      context: ./php
    volumes:
      - ./cylonnet:/var/www/html
      - ./php/conf.d/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - cylonnet-net
    environment:
      - PHP_FPM_LISTEN=9000
    depends_on:
      - db

  db:
    image: mariadb:latest
    volumes:
      - ./mariadb/mariadb:/var/lib/mysql
      - ./mariadb/initdb:/docker-entrypoint-initdb.d 
    environment:
      MYSQL_ROOT_PASSWORD: cambia_esto
      MYSQL_DATABASE: CYLONNet
      MYSQL_USER: cylon_adm
      MYSQL_PASSWORD: cambia_esto
    networks:
      - cylonnet-net
    depends_on:
      - orquestador

  orquestador:
    build:
      context: ./orquestador
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./cylonnet/assets/sh:/app/sh
      - ./nginx/conf.d:/app/nginx/conf.d
    networks:
      - cylonnet-net
    ports:
      - "8000:8000"   # API HTTP

networks:
  cylonnet-net: